# Generated by Django 3.2.8 on 2022-06-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20220616_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
