# Generated by Django 3.2.8 on 2022-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolistitem',
        ),
    ]
